// 안내 화면이 쓰는 목록. data/works.json + 벡터스토어에서 만들어진다 — 손으로 고치지 말 것.
// ⚠️ 여기 실린 것은 **화면에 보여 줄 대표 작품**이지 챗봇이 아는 범위가 아니다.
//    챗봇이 아는 범위 = myth-docs-*.json (아래 CORPUS).

export type Work = {
  slug: string; url: string; title: string;
  artist: string; era: string; chunks: number; myth: string; code: string;
};

export const THUMB = (slug: string) =>
  `https://myth-gallery.vercel.app/img/works/thumb/${slug}.webp`;

export const WORKS: Work[] = [
  {
    slug: "greek-0a50eec5ef",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-0a50eec5ef",
    title: "헤라클레스와 켄타우로스 네소스",
    artist: "잠볼로냐",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-2be2a8a891",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-2be2a8a891",
    title: "아폴론과 다프네",
    artist: "안토니오 델 폴라이올로",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-22ddc6d999",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-22ddc6d999",
    title: "페르가몬 제단 동쪽 프리즈 — 아테나, 알퀴오네우스, 가이아, 니케",
    artist: "익명",
    era: "고대 기원전 700년~기원후 400년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-35001919e7",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-35001919e7",
    title: "케이론과 아킬레우스",
    artist: "존 싱어 사전트",
    era: "근현대 1900년~",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-199855cc84",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-199855cc84",
    title: "마르스와 미네르바의 싸움 (아테나가 아레스를 쓰러뜨림 — 아프로디테 동반)",
    artist: "조제프 브누아 쉬베",
    era: "신고전주의 1750년~1830년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-4d0ef2d28f",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-4d0ef2d28f",
    title: "헥토르의 시신 앞에 슬퍼하는 안드로마케",
    artist: "자크 루이 다비드",
    era: "신고전주의 1750년~1830년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-17b732695d",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-17b732695d",
    title: "큐피드와 프시케",
    artist: "안토니 반 다이크",
    era: "바로크 1600년~1750년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-4612f58e9a",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-4612f58e9a",
    title: "아폴론과 디아나",
    artist: "알브레히트 뒤러",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-2a03908f61",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-2a03908f61",
    title: "피그말리온과 갈라테이아",
    artist: "에티엔 모리스 팔코네",
    era: "신고전주의 1750년~1830년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-4ce2204d18",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-4ce2204d18",
    title: "다이달로스와 이카로스",
    artist: "프레더릭 레이턴",
    era: "19세기 후반 1850년~1910년",
    chunks: 3,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-09374e014c",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-09374e014c",
    title: "유피테르, 메르쿠리우스, 비르투스",
    artist: "도소 도시",
    era: "르네상스 1400년~1600년",
    chunks: 3,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-258c8f4fe1",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-258c8f4fe1",
    title: "안드로메다를 구하는 페르세우스",
    artist: "피에로 디 코지모",
    era: "르네상스 1400년~1600년",
    chunks: 3,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "norse-6d4f4262bf",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-6d4f4262bf",
    title: "시구르드와 헬가 (「황금 갈기 말 굴팍시와 칼 군포데르」 삽화)",
    artist: "헨리 저스티스 포드",
    era: "근현대 (북유럽) 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-4d076fe1d0",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-4d076fe1d0",
    title: "〈신들의 황혼 — 브륀힐데, 3막〉 (의상·장면 디자인)",
    artist: "하인리히 레플러",
    era: "근현대 (북유럽) 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-471d9b3cad",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-471d9b3cad",
    title: "미드가르드 뱀과 싸우는 토르",
    artist: "요한 하인리히 퓌슬리",
    era: "근세 수용 1500년~1800년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-7e6fdb30e1",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-7e6fdb30e1",
    title: "노른에게 묻는 미미르와 발드르",
    artist: "헤르만 에른스트 프로인트",
    era: "낭만주의 (북유럽) 1830년~1870년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-ab8aec3965",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-ab8aec3965",
    title: "〈펜리르와 티르〉 (필사본 도상, SÁM 66 fol. 78v)",
    artist: "야콥 시구르드손",
    era: "근세 수용 1500년~1800년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-f28acd5247",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-f28acd5247",
    title: "헬 앞의 헤르모드",
    artist: "존 찰스 돌만",
    era: "근현대 (북유럽) 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-9407c96609",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-9407c96609",
    title: "시구르드와 용 파프니르",
    artist: "익명",
    era: "바이킹기 고대 800년~1300년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-a882b6a705",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-a882b6a705",
    title: "〈아우둠라와 부리〉 (필사본 도상, SÁM 66 74r)",
    artist: "야콥 시구르드손",
    era: "근세 수용 1500년~1800년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-62980b6e2c",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-62980b6e2c",
    title: "아스가르드에서 장난친 로키 (시프의 머리카락을 자르는 로키)",
    artist: "윌리 포가니",
    era: "근현대 (북유럽) 1900년~",
    chunks: 3,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-8e8c0980ce",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-8e8c0980ce",
    title: "이미르를 핥는 원초의 암소 아우둠라",
    artist: "니콜라이 아빌고르",
    era: "근세 수용 1500년~1800년",
    chunks: 3,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-8d9e15c69f",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-8d9e15c69f",
    title: "오딘과 바프스루드니르",
    artist: "로렌츠 프뢸리히",
    era: "낭만주의 (북유럽) 1830년~1870년",
    chunks: 3,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-ebbdb29e62",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-ebbdb29e62",
    title: "프레이야로 분장한 토르",
    artist: "카를 라르손",
    era: "민족낭만주의 1870년~1900년",
    chunks: 3,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "egypt-4930c5fceb",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-4930c5fceb",
    title: "아니의 사자의 서 — 오시리스 심판 (심장 무게 달기)",
    artist: "익명",
    era: "신왕국 기원전 1550년~기원전 1069년",
    chunks: 3,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-42cb99f8f5",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-42cb99f8f5",
    title: "고양이로 변신한 라가 아펩(아포피스)을 죽이는 장면",
    artist: "작자 미상",
    era: "신왕국 기원전 1550년~기원전 1069년",
    chunks: 3,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-2cf20f2f9f",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-2cf20f2f9f",
    title: "우드자트 (호루스의 눈) 부적",
    artist: "익명",
    era: "말기 왕조 기원전 664년~기원전 332년",
    chunks: 2,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-e8e88fb2cb",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-e8e88fb2cb",
    title: "세트가 아펩(아포피스)을 창으로 찌르다",
    artist: "작자 미상",
    era: "신왕국 기원전 1550년~기원전 1069년",
    chunks: 2,
    myth: "이집트",
    code: "egypt",
  },
];

/** 아카이브 전체와 수록 현황 */
export const MYTHS = [
  { name: "그리스·로마", code: "greek", works: 469, covered: 20 },
  { name: "힌두", code: "hindu", works: 120, covered: 0 },
  { name: "북유럽", code: "norse", works: 117, covered: 19 },
  { name: "중국", code: "chinese", works: 113, covered: 0 },
  { name: "이집트", code: "egypt", works: 92, covered: 4 },
  { name: "메소포타미아", code: "meso", works: 71, covered: 0 },
];

/** 벡터스토어에 실제로 든 양 — 화면 문구가 이 숫자를 쓴다 */
export const CORPUS = { works: 43, chunks: 130, archive: 982 };
