// 안내 화면이 쓰는 목록. ⚠️ **손으로 고치지 말 것** — `python tools/build-works.py` 로 만든다.
//    입력 = data/chunks.json + myth-docs-index.json. 벡터스토어가 바뀌면 다시 돌린다.
// ⚠️ 여기 실린 것은 **화면에 보여 줄 대표 작품**이지 챗봇이 아는 범위가 아니다.
//    챗봇이 아는 범위 = myth-docs-*.json (아래 CORPUS).

export type Work = {
  slug: string; url: string; title: string;
  artist: string; era: string; chunks: number; myth: string; code: string;
};

export const THUMB = (slug: string) =>
  `https://myth-gallery.vercel.app/img/works/thumb/${slug}.webp`;

export const WORKS: Work[] = [
  {
    slug: "greek-4d28822aaf",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-4d28822aaf",
    title: "가니메데스의 납치",
    artist: "미켈란젤로 부오나로티",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-9fe37759e5",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-9fe37759e5",
    title: "갈라테아",
    artist: "귀스타브 모로",
    era: "19세기 후반 1850년~1910년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-f7366f7a6f",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-f7366f7a6f",
    title: "갈림길의 헤라클레스",
    artist: "폼페오 바토니",
    era: "신고전주의 1750년~1830년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-5e38acc683",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-5e38acc683",
    title: "나는 메르쿠리우스",
    artist: "잠볼로냐",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-3a6a537318",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-3a6a537318",
    title: "넵투누스 분수의 넵투누스",
    artist: "바르톨로메오 암만나티",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-96bb15e940",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-96bb15e940",
    title: "넵투누스와 암피트리테",
    artist: "얀 호사르트",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-ceac2f71e4",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-ceac2f71e4",
    title: "누드의 전투 (누드 남성들의 전투)",
    artist: "안토니오 델 폴라이올로",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-f381767fb1",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-f381767fb1",
    title: "님프 (님프의 우물)",
    artist: "윌리엄 아돌프 부그로",
    era: "19세기 후반 1850년~1910년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-41bcec5048",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-41bcec5048",
    title: "님프와 목동",
    artist: "티치아노 베첼리오",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-f78f8cdcb8",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-f78f8cdcb8",
    title: "다나에",
    artist: "렘브란트 판 레인",
    era: "바로크 1600년~1750년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-f26e84a6da",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-f26e84a6da",
    title: "다나에",
    artist: "얀 호사르트",
    era: "르네상스 1400년~1600년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "greek-02746781c1",
    url: "https://myth-gallery.vercel.app/ko/greek/works/greek-02746781c1",
    title: "데우칼리온과 피라",
    artist: "페테르 파울 루벤스",
    era: "바로크 1600년~1750년",
    chunks: 4,
    myth: "그리스·로마",
    code: "greek",
  },
  {
    slug: "hindu-a3e44b5125",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-a3e44b5125",
    title: "〈고바르단 산을 들어올리는 크리슈나〉",
    artist: "작자 미상",
    era: "무굴 1526년~1857년",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-b77319d3e8",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-b77319d3e8",
    title: "〈두 바이슈나바〉",
    artist: "자미니 로이",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-9ec8029898",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-9ec8029898",
    title: "〈라다〉",
    artist: "수나야니 데비",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-8b6c5a39bf",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-8b6c5a39bf",
    title: "〈라다와 크리슈나〉",
    artist: "크시틴드라나트 마줌다르",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-54436cf556",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-54436cf556",
    title: "〈라마, 시타, 락슈마나〉",
    artist: "작자 미상",
    era: "무굴 1526년~1857년",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-22a0bbe8ad",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-22a0bbe8ad",
    title: "〈라마의 혼인〉",
    artist: "케샤바이아 벤카탑파",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-e12b727f91",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-e12b727f91",
    title: "〈란카의 전투〉 (메와르 라마야나 「유다 칸다」 폴리오)",
    artist: "사히브딘",
    era: "무굴 1526년~1857년",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-8ccfa1da57",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-8ccfa1da57",
    title: "〈바라나시의 사원과 목욕 가트〉",
    artist: "에드윈 로드 윅스",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-cae506376d",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-cae506376d",
    title: "〈바라트 마타〉 (인도 어머니)",
    artist: "아바닌드라나트 타고르",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-4020bf4a24",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-4020bf4a24",
    title: "〈바라하와 히란야크샤의 전투〉",
    artist: "마나쿠",
    era: "무굴 1526년~1857년",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-70437c7502",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-70437c7502",
    title: "〈바스트라 하란 — 옷을 훔치는 크리슈나〉",
    artist: "바마파다 바네르지",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "hindu-ac208f40e8",
    url: "https://myth-gallery.vercel.app/ko/hindu/works/hindu-ac208f40e8",
    title: "〈부상당한 새와 싯다르타〉",
    artist: "아시타 쿠마르 할다르",
    era: "근현대 1857년~",
    chunks: 4,
    myth: "힌두",
    code: "hindu",
  },
  {
    slug: "chinese-d15d535312",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-d15d535312",
    title: "〈갈치천이거도〉",
    artist: "왕몽",
    era: "원 1271 — 1368",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-4be2377782",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-4be2377782",
    title: "〈괵국부인유춘도〉",
    artist: "장훤",
    era: "당·송 618 — 1279",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-99c4607b13",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-99c4607b13",
    title: "〈구가도〉",
    artist: "장악",
    era: "원 1271 — 1368",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-f7b789a34c",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-f7b789a34c",
    title: "〈구가도권〉",
    artist: "이공린",
    era: "당·송 618 — 1279",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-c155ea4079",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-c155ea4079",
    title: "〈귀도책 (歸棹冊)〉 중 1엽 — 강 위의 귀환",
    artist: "석도",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-9f271d5e0e",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-9f271d5e0e",
    title: "〈귀취도〉",
    artist: "나빙",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-908c864cfd",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-908c864cfd",
    title: "〈나한도 (羅漢圖)〉",
    artist: "김정표",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-052bd695be",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-052bd695be",
    title: "〈낙신도〉",
    artist: "임웅",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-f2f3a68c42",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-f2f3a68c42",
    title: "〈남극노인도 (南極老人圖)〉",
    artist: "냉매",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-435abad858",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-435abad858",
    title: "〈도교 신선의 바둑〉",
    artist: "대진",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-4c93f2534d",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-4c93f2534d",
    title: "〈마고선인도〉",
    artist: "마화지",
    era: "당·송 618 — 1279",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "chinese-8ccba54394",
    url: "https://myth-gallery.vercel.app/ko/chinese/works/chinese-8ccba54394",
    title: "〈마고헌수도 (麻姑獻壽圖)〉",
    artist: "황신",
    era: "명·청 1368 — 1912",
    chunks: 4,
    myth: "중국",
    code: "chinese",
  },
  {
    slug: "norse-aa60789a47",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-aa60789a47",
    title: "〈남편을 찾는 프레이야〉",
    artist: "닐스 블롬메르",
    era: "낭만주의 (북유럽) 1830년~1870년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-e93cd5d9b7",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-e93cd5d9b7",
    title: "〈라그나로크〉",
    artist: "루이스 모에",
    era: "민족낭만주의 1870년~1900년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-f72869fc84",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-f72869fc84",
    title: "〈라인의 황금 — 발할 무대 디자인〉",
    artist: "헤르만 부르크하르트",
    era: "민족낭만주의 1870년~1900년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-3b7d151f39",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-3b7d151f39",
    title: "〈란의 딸들〉",
    artist: "한스 달",
    era: "상징주의·근대 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-e27f4a1d06",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-e27f4a1d06",
    title: "〈물푸레나무 위그드라실 — 세계수〉",
    artist: "프리드리히 빌헬름 하이네",
    era: "민족낭만주의 1870년~1900년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-a8ae5f610c",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-a8ae5f610c",
    title: "〈발퀴레〉",
    artist: "로베르트 엥엘스",
    era: "근현대 (북유럽) 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-4fb26b9f0c",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-4fb26b9f0c",
    title: "〈뱀 구덩이의 라그나르 로드브로크〉",
    artist: "위고 해밀턴",
    era: "낭만주의 (북유럽) 1830년~1870년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-66d71c103c",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-66d71c103c",
    title: "〈보탄과 잠든 브륀힐데〉",
    artist: "페르디난트 레케",
    era: "민족낭만주의 1870년~1900년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-34f0280939",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-34f0280939",
    title: "〈스웨덴에 도착한 오딘과 길피의 결합〉",
    artist: "위고 해밀턴",
    era: "낭만주의 (북유럽) 1830년~1870년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-4d076fe1d0",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-4d076fe1d0",
    title: "〈신들의 황혼 — 브륀힐데, 3막〉 (의상·장면 디자인)",
    artist: "하인리히 레플러",
    era: "근현대 (북유럽) 1900년~",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-c766b126c9",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-c766b126c9",
    title: "〈아메리카를 발견하는 레이프 에이릭손〉",
    artist: "크리스티안 크로그",
    era: "민족낭만주의 1870년~1900년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "norse-a882b6a705",
    url: "https://myth-gallery.vercel.app/ko/norse/works/norse-a882b6a705",
    title: "〈아우둠라와 부리〉 (필사본 도상, SÁM 66 74r)",
    artist: "야콥 시구르드손",
    era: "근세 수용 1500년~1800년",
    chunks: 4,
    myth: "북유럽",
    code: "norse",
  },
  {
    slug: "egypt-afe8377444",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-afe8377444",
    title: "〈고대 이집트의 여가 (3000년 전)〉",
    artist: "로런스 알마-타데마",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-4a9a0f77d3",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-4a9a0f77d3",
    title: "〈모세의 발견〉",
    artist: "에드윈 롱",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-511f60c032",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-511f60c032",
    title: "〈셉타 무덤 왕가의 계곡 벽화 모사〉",
    artist: "조지프 린던 스미스",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-618b0d16ef",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-618b0d16ef",
    title: "〈스핑크스와 대피라미드 전경 (남동쪽에서)〉",
    artist: "드크립시옹 드 레집트",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-4963d39a4f",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-4963d39a4f",
    title: "〈신들과 그 제작자들〉",
    artist: "에드윈 롱",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-7fd8db4192",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-7fd8db4192",
    title: "〈아피스 황소 행렬〉",
    artist: "프레더릭 아서 브리지먼",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-a3cee5d81f",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-a3cee5d81f",
    title: "〈이집트 고양이의 장례〉",
    artist: "존 라인하르트 웨귈린",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-e5fcf8bc5b",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-e5fcf8bc5b",
    title: "〈이집트의 과부〉",
    artist: "로런스 알마-타데마",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-832b3484cf",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-832b3484cf",
    title: "〈이집트의 풍요〉",
    artist: "윌리엄 홀먼 헌트",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-08152963c7",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-08152963c7",
    title: "〈카르나크 대열주실〉",
    artist: "데이비드 로버츠",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-25c23b320b",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-25c23b320b",
    title: "관문의 서 「네 인종」 (세티 1세 무덤)",
    artist: "작자 미상",
    era: "신왕국 기원전 1550년~기원전 1069년",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "egypt-309c92bc87",
    url: "https://myth-gallery.vercel.app/ko/egypt/works/egypt-309c92bc87",
    title: "나일신 하피 상반신상",
    artist: "익명",
    era: "중왕국 기원전 2055년~기원전 1650년",
    chunks: 4,
    myth: "이집트",
    code: "egypt",
  },
  {
    slug: "meso-fd4b3f26d4",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-fd4b3f26d4",
    title: "〈「이교의 신들」 습작 (보스턴 공공도서관 벽화)〉",
    artist: "존 싱어 사전트",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-85c04b72e9",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-85c04b72e9",
    title: "〈니느웨의 몰락 (메조틴트)〉",
    artist: "존 마틴",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-a945704da5",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-a945704da5",
    title: "〈레이디 릴리스〉",
    artist: "단테 가브리엘 로세티",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-5ad8fb433a",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-5ad8fb433a",
    title: "〈바빌론 반란 소식을 받는 세미라미스〉",
    artist: "구에르치노",
    era: "근세 수용 1500년~1800년",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-7608506e24",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-7608506e24",
    title: "〈바빌론 유수〉",
    artist: "외젠 들라크루아",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-abeebade78",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-abeebade78",
    title: "〈바빌론의 몰락〉",
    artist: "존 마틴",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-5534407ef6",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-5534407ef6",
    title: "〈벽에 쓰인 글씨를 해석하는 다니엘〉",
    artist: "귀스타브 도레",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-b4e2a6d41b",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-b4e2a6d41b",
    title: "〈사르다나팔루스의 죽음〉",
    artist: "외젠 들라크루아",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-02da54fdc2",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-02da54fdc2",
    title: "〈산헤립 군대의 전멸〉",
    artist: "귀스타브 도레",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-f7d33a9119",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-f7d33a9119",
    title: "〈세미라미스〉",
    artist: "체사레 사카지",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-c2d22ca297",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-c2d22ca297",
    title: "나보니두스 비석",
    artist: "작자 미상",
    era: "신바빌로니아 기원전 600년~기원전 539년",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
  {
    slug: "meso-b2efba12e6",
    url: "https://myth-gallery.vercel.app/ko/meso/works/meso-b2efba12e6",
    title: "리디아의 왕 칸다울레스, 자신의 부인을 신하 기게스에게 몰래 보여주다",
    artist: "윌리엄 에티",
    era: "근대 수용 1800년~",
    chunks: 4,
    myth: "메소포타미아",
    code: "meso",
  },
];

/** 아카이브 전체와 그중 챗봇이 아는 만큼 — 화면 문구가 이 숫자를 쓴다 */
export const MYTHS = [
  { name: "그리스·로마", code: "greek", works: 469, covered: 469 },
  { name: "힌두", code: "hindu", works: 120, covered: 120 },
  { name: "중국", code: "chinese", works: 113, covered: 113 },
  { name: "북유럽", code: "norse", works: 117, covered: 117 },
  { name: "이집트", code: "egypt", works: 92, covered: 92 },
  { name: "메소포타미아", code: "meso", works: 71, covered: 71 },
];

/** 벡터스토어에 실제로 든 양 — 화면 문구가 이 숫자를 쓴다 */
export const CORPUS = { works: 982, chunks: 2978, archive: 982 };
